import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:river_flow/services/firestore_service.dart';
import 'package:river_flow/models/river_data_model.dart';

export 'package:river_flow/models/river_data_model.dart' show AlertLevel;

/// Snapshot of the river sensor reading for compatibility.
class RiverReading {
  const RiverReading({
    required this.waterLevelMeters,
    required this.maxLevelMeters,
    required this.alertLevel,
    required this.timestamp,
    required this.riseRatePerHour,
    required this.sensorOnline,
  });

  final double waterLevelMeters;
  final double maxLevelMeters;
  final AlertLevel alertLevel;
  final DateTime timestamp;
  final double riseRatePerHour;
  final bool sensorOnline;

  /// Water level as 0.0 – 1.0 fraction.
  double get percentage => (waterLevelMeters / maxLevelMeters).clamp(0.0, 1.0);

  /// Human‑readable label for the current alert.
  String get alertLabel {
    switch (alertLevel) {
      case AlertLevel.safe:
        return 'SAFE';
      case AlertLevel.monitor:
        return 'MONITOR';
      case AlertLevel.prepare:
        return 'PREPARE TO EVACUATE';
      case AlertLevel.evacuate:
        return 'EVACUATE NOW';
    }
  }

  /// Convert RiverReading to RiverDataModel for saving to Firestore.
  RiverDataModel toRiverDataModel() {
    return RiverDataModel(
      recordId: '', // Will be generated by Firestore
      waterLevel: waterLevelMeters,
      percentage: percentage,
      alertLevel: alertLevel,
      timestamp: timestamp,
      riseRatePerHour: riseRatePerHour,
      sensorOnline: sensorOnline,
      maxLevel: maxLevelMeters,
    );
  }

  /// Create RiverReading from RiverDataModel.
  factory RiverReading.fromRiverDataModel(RiverDataModel model) {
    return RiverReading(
      waterLevelMeters: model.waterLevel,
      maxLevelMeters: model.maxLevel,
      alertLevel: model.alertLevel,
      timestamp: model.timestamp,
      riseRatePerHour: model.riseRatePerHour,
      sensorOnline: model.sensorOnline,
    );
  }
}

/// Provides a stream of river sensor data from Firestore.
/// Listens to real-time updates from the river_data collection.
class RiverDataService {
  RiverDataService._();
  static final RiverDataService instance = RiverDataService._();

  final FirestoreService _firestoreService = FirestoreService.instance;

  StreamSubscription<RiverDataModel?>? _latestReadingSubscription;
  final _controller = StreamController<RiverReading>.broadcast();

  /// Emits updates whenever new readings arrive from Firestore.
  Stream<RiverReading> get readings {
    _ensureListening();
    return _controller.stream;
  }

  /// Most recent reading (useful for one‑shot display).
  RiverReading? _lastReading;
  RiverReading? get lastReading => _lastReading;

  RiverReading _fallbackReading() {
    return RiverReading(
      waterLevelMeters: 0,
      maxLevelMeters: 10,
      alertLevel: AlertLevel.safe,
      timestamp: DateTime.now(),
      riseRatePerHour: 0,
      sensorOnline: false,
    );
  }

  /// Fetch the latest reading from Firestore.
  Future<void> refresh() async {
    try {
      final latestModel = await _firestoreService.getLatestRiverReading();
      if (latestModel != null) {
        _lastReading = RiverReading.fromRiverDataModel(latestModel);
        _controller.add(_lastReading!);
      } else {
        _lastReading ??= _fallbackReading();
        _controller.add(_lastReading!);
      }
    } catch (e) {
      debugPrint('RiverDataService: refresh failed: $e');
      _lastReading ??= _fallbackReading();
      if (!_controller.isClosed) {
        _controller.add(_lastReading!);
      }
    }
  }

  /// Listen to real-time updates from Firestore.
  void _ensureListening() {
    if (_latestReadingSubscription != null) return;

    _latestReadingSubscription = _firestoreService
        .watchLatestRiverReading()
        .listen(
          (latestModel) {
            if (latestModel != null) {
              final reading = RiverReading.fromRiverDataModel(latestModel);
              _lastReading = reading;
              _controller.add(reading);
            } else {
              _lastReading ??= _fallbackReading();
              if (!_controller.isClosed) {
                _controller.add(_lastReading!);
              }
            }
          },
          onError: (error) {
            debugPrint('RiverDataService: stream error: $error');
            _lastReading ??= _fallbackReading();
            if (!_controller.isClosed) {
              _controller.add(_lastReading!);
            }
          },
        );

    if (_lastReading == null && !_controller.isClosed) {
      _lastReading = _fallbackReading();
      _controller.add(_lastReading!);
    }
  }

  /// Stop listening to updates and clean up resources.
  void dispose() {
    _latestReadingSubscription?.cancel();
    _controller.close();
  }

  /// Manually add a river reading to Firestore.
  /// Usually called by admin or sensor systems.
  Future<void> addReading(RiverReading reading) async {
    try {
      final model = reading.toRiverDataModel();
      await _firestoreService.addRiverReading(model);
    } catch (e) {
      throw Exception('Failed to add river reading: $e');
    }
  }
}
