// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes the Firebase configuration options for the current platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtxdxJd7d_example',
    appId: '1:452133115890:android:6fd7e401ad850f2dc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    databaseURL: 'https://riverflow-sentinel.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxc3cMxample',
    appId: '1:452133115890:ios:21d414475c57623bc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    databaseURL: 'https://riverflow-sentinel.firebaseio.com',
    iosBundleId: 'com.example.riverFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxc3cMxample',
    appId: '1:452133115890:ios:21d414475c57623bc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    databaseURL: 'https://riverflow-sentinel.firebaseio.com',
    iosBundleId: 'com.example.riverFlow',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qWxample',
    appId: '1:452133115890:web:1e060d0d725a4a9fc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    databaseURL: 'https://riverflow-sentinel.firebaseio.com',
    authDomain: 'riverflow-sentinel.firebaseapp.com',
    storageBucket: 'riverflow-sentinel.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qWxample',
    appId: '1:452133115890:web:497bc02d329145bfc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    databaseURL: 'https://riverflow-sentinel.firebaseio.com',
    authDomain: 'riverflow-sentinel.firebaseapp.com',
    storageBucket: 'riverflow-sentinel.appspot.com',
  );
}
