// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWks_sgbtVNFJMltFD2Z_fiyN4YNEn39A',
    appId: '1:452133115890:web:1e060d0d725a4a9fc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    authDomain: 'riverflow-sentinel.firebaseapp.com',
    databaseURL: 'https://riverflow-sentinel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riverflow-sentinel.firebasestorage.app',
    measurementId: 'G-CTKZ4HBT54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnhz5ZmKUL81t2bGjjBJ4UzuRLHslIawY',
    appId: '1:452133115890:android:6fd7e401ad850f2dc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    databaseURL: 'https://riverflow-sentinel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riverflow-sentinel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEUq2SMI1ei6rGJP3LUi3wsp5TjqoNCK4',
    appId: '1:452133115890:ios:21d414475c57623bc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    databaseURL: 'https://riverflow-sentinel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riverflow-sentinel.firebasestorage.app',
    iosClientId: '452133115890-emi3vv6mqjtefqdbsvvaf8uhomqfa4mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEUq2SMI1ei6rGJP3LUi3wsp5TjqoNCK4',
    appId: '1:452133115890:ios:21d414475c57623bc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    databaseURL: 'https://riverflow-sentinel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riverflow-sentinel.firebasestorage.app',
    iosClientId: '452133115890-emi3vv6mqjtefqdbsvvaf8uhomqfa4mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWks_sgbtVNFJMltFD2Z_fiyN4YNEn39A',
    appId: '1:452133115890:web:497bc02d329145bfc9fd6b',
    messagingSenderId: '452133115890',
    projectId: 'riverflow-sentinel',
    authDomain: 'riverflow-sentinel.firebaseapp.com',
    databaseURL: 'https://riverflow-sentinel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riverflow-sentinel.firebasestorage.app',
    measurementId: 'G-CTLHK4ND6G',
  );
}
